general.import=["~/.config/alacritty/colorschemes/gruvbox/material.toml"]

[font]
normal = { family = "FiraCode", style  = "SemiBold" }
#normal = { family = "JetBrainsMono Nerd Font Propo", style  = "SemiBold" }
bold= { family = "JetBrainsMono Nerd Font Propo", style  = "ExtraBold" }
italic= { family = "JetBrainsMono Nerd Font Propo", style  = "SemiBold Italic" }
bold_italic= { family = "JetBrainsMono Nerd Font Propo", style  = "ExtraBold Italic" }
size = 11

[env]
term = "xterm-256color"

[terminal.shell]
program = "/bin/bash"

[window]
opacity = 0.99
blur = true
decorations = "None"

[window.padding]
x = 15
y = 15


[keyboard]
bindings = [
#Resizing
{key = "Backspace", mods = "Control|Shift", action = "ResetFontSize"},
{key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize"},
{key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize"},

#Scrolling
{key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp"},
{key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown"},
{key = "Enter", mods = "Control|Shift", action = "CreateNewWindow"},
]
